### ISSUE TITLE
readline now requires Stream#listenerCount()

### ISSUE THREAD

**Issue by jclulow** [jclulow/node-progbar#17]
In newer node versions (i.e. after _v0.12.X), the `readline` module appears to make use of the `listenerCount()` method on a `Stream`.  On platforms where we fall back to `readline` instead of making direct use of `/dev/tty`, this causes the following failure:

```
$ node tests/harness.js
readline.js:952
  if (stream.listenerCount('keypress') > 0) {
             ^

TypeError: stream.listenerCount is not a function
    at Object.emitKeypressEvents (readline.js:952:14)
    at new Interface (readline.js:126:13)
    at Object.exports.createInterface (readline.js:24:10)
    at init_readline (/Users/jclulow/proj/node-progbar/lib/progbar.js:165:22)
    at new ProgressBar (/Users/jclulow/proj/node-progbar/lib/progbar.js:238:18)
    at null._repeat (/Users/jclulow/proj/node-progbar/tests/harness.js:20:13)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
```

The fake `stdin` stream passed to `readline` should include a `listenerCount()` stub which always returns `0`.

**Comment by jclulow** [comment]
Published `progbar@1.1.1` to NPM with the fix.
